__author__ = 'Shannon Jaeger'
__version__ = '0.0.1'

from ImisFile import ImisFile
import argparse
import random
import shutil
import time

# TODO move from a csv file to a SqLite DB

def update_data(current_file_path=None, new_data_file_path=None, make_backup=True):
    """
    Merge copy of iMIS data with a new updated iMIS file.

    The new updated file is assumed to be the more up-to-date file, typically it
    will be a report generated by the Girl Guides iMIS system
    :param current_file_path: A properly constructed path to the file currently being
    used for iMIS number selection
    :param new_data_file_path: A properly constructed file path containing the new
    iMIS data
    :return: True if the current file has been updated, False otherwise
    """

    imis_file = ImisFile(current_file_path)
    imis_file.merge(new_data_file_path)


    #print("          ACTIVE MEMBERS")
    #print("--------------------------------------------------------")
    #for member in imis_file.active_member_list:
    #    print(str(member))

    #print("\n\n          INACTIVE MEMBERS")
    #print("--------------------------------------------------------")
    #for member in imis_file.inactive_member_list:
    #    print(str(member))


    # TODO verify the correctness of the new file
    if make_backup:
        shutil.copy(current_file_path, current_file_path+".bk")
    imis_file.write()

def select_numbers(file_path=None, how_many=3, make_backup=False, use_all=False):
    """
    Select a set of iMIS numbers from the given file.

    :param file_path:  The data file
    :param how_many:
    :param use_all:
    :return list: List of ImisFile.Member instances, the selected Members
    """

    # Read in the iMIS data
    imis_file = ImisFile(file_path)

    # Set-up the random number generator
    random.seed()
    random.randrange(0, len(imis_file.active_member_list))

    # Select the desired number of iMIS numbers
    selected_members = []
    while len(selected_members) < how_many:
        new_idx = random.randint(0, len(imis_file.active_member_list))
        member = imis_file.active_member_list[new_idx]
        if use_all or len(member.dates_selected) < 1:
            # We select this one.
            if len(member.dates_selected) < 1:
                member.dates_selected = time.strftime("%Y%m%d")
            else:
                member.dates_selected += ':' + time.strftime("%Y%m%d")
            selected_members.append(member)

    if make_backup:
        shutil.copy(file_path, file_path+".bk")
    imis_file.write()

    print('Selected Members')
    print('---------------------')
    for member in selected_members:
        print(str(member))

    return selected_members


def main():
    """
    The main function of the whole program.  The arguments used when calling the
    application determines which mode it is run in as well as the files that are
    used for processing.

    Modes
    ----------
    1. iMIS random number selection:  Select a specified number of iMIS numbers
       from the provided iMIS data file at random
    2. iMIS data file update: Update the iMIS data file being used for number
       selection from an updated iMIS member list

    Command-line Arguments
    --------------------------
    -i <file_path> iMIS data file for number selection
    -n <integer> number of random iMIS numbers to be selected
    -r if listed then re-use iMIS numbers that have been selected before.
    -b Create a backup iMIS data file before writing

    -c <file_path> Current iMIS data file being used for number selection
    -m <file_path> New iMIS member list
    -b Create a backup iMIS data file before writing

    :return: None
    """
    parser = argparse.ArgumentParser(description='iMIS number selector and data file manager.')
    parser.add_argument('-version', action='version', version='%(prog)s '+str(__version__))
    parser.add_argument('-i', dest='imis_file',
                        help='Fully specified file path to the iMIS data file in csv format.')
    parser.add_argument('-n', type=int, dest='num', default='10',
                        help='Number of iMIS numbers to select.')


    parser.add_argument('-c', type=str, dest='current_imis_file',
                        help='Fully specified file path to the iMIS data file in csv format.')
    parser.add_argument('-m', type=str, dest='imis_member_file',
                        help='Fully specified file path to the iMIS Member List in csv format.')

    parser.add_argument('-r', action='store_true', dest='reuse',
                        help='If provided, re-use previously selected iMIS numbers.')
    parser.add_argument('-b', action='store_true', dest='backup',
                        help='If provided, backup any altered iMIS data file.')

    args = parser.parse_args()
    if args.imis_file:
        select_numbers(args.imis_file, args.num, args.backup, args.reuse)
    elif args.current_imis_file:
        update_data(args.current_imis_file, args.imis_member_file, args.backup)
    else:
        parser.error("One of -i or -c must be specified.")




if __name__ == '__main__':
    main()